### PR TITLE
Update translationManager.ts

### PR DESCRIPTION
**Pull request by milotype**
Add Croatian locale

### CODE REVIEW

**Comment by Winbee** [comment]
Hello @milotype thanks for your contribution. Unfortunately, I won't be able to merge it as is because this language needs to be present in the d3 library I use here: https://github.com/d3/d3-time-format/tree/main/locale. Once the `hr-HR.json` will be present in the library then it's all good.

**Comment by milotype** [comment]
I've just made the Croatian translation for it with a PR at https://github.com/d3/d3-time-format/pull/106
If you want, I could inform you when it's merged, or you can do it yourself.

Cheers, Milo

**Comment by Winbee** [comment]
Awesome! I'd be happy if you can ping me when it's done. We will need to update the version of d3 in the `package.json` of `joplin-turn-to-chart` to take that change into account.

**Comment by milotype** [comment]
@Winbee
Croatian is translated and released at:
https://github.com/d3/d3-time-format/blob/main/locale/hr-HR.json

**Comment by Winbee** [comment]
Hello @milotype, good new thanks. I've updated the library in another commit as the current PR has conflicts and it needed other package-lock.json changes. You will be able to find the Croatian locale in the version `v1.5.0`.

**Pull request closed without merging**
